const questions=["毎日または毎週、同じPC作業を繰り返している？","ExcelやCSVのコピー・転記が多い？","ファイル整理や書類作成を手作業で行っている？","作業手順はある程度決まっている？","その作業に時間や負担を感じている？"];
const choices=[['yes','はい','当てはまる'],['no','いいえ','当てはまらない'],['unknown','わからない','判断がつかない']];
const app=document.querySelector('#app');let step=-1;let answers=Array(5).fill(null);
const params=new URLSearchParams(location.search);const raw=(params.get('utm_source')||'direct').toLowerCase();const source=['youtube','instagram','tiktok','note'].includes(raw)?raw:(raw==='direct'?'direct':'other');
function track(event){const body=JSON.stringify({event,source,medium:params.get('utm_medium'),campaign:params.get('utm_campaign'),content:params.get('utm_content'),landing_variant:params.get('landing_variant')});if(navigator.sendBeacon)navigator.sendBeacon('/api/diagnosis-event',new Blob([body],{type:'application/json'}));else fetch('/api/diagnosis-event',{method:'POST',headers:{'content-type':'application/json'},body,keepalive:true}).catch(()=>{});}
function esc(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function start(){step=0;track('start');render()}function choose(v){answers[step]=v;if(step===4){step=5;track('complete')}else step++;render()}
function result(){const yes=answers.filter(v=>v==='yes').length,unknown=answers.filter(v=>v==='unknown').length;if(yes>=4)return['自動化を検討しやすい作業です','繰り返し・転記・手順が決まった作業が多く、自動化の候補になりそうです。',['Excel・CSVの転記や集計','定型書類の作成・保存','ファイル名変更やフォルダ整理']];if(yes>=2||unknown>=2)return['条件を整理すれば検討できそうです','作業の一部を自動化できる可能性があります。まず手順と例外を整理するのがおすすめです。',['繰り返し部分だけの自動化','入力チェックや集計の補助','作業手順の見える化']];return['今は整理から始めるのがおすすめです','毎回の判断が多い作業は、全部を自動化するより補助機能から検討すると安全です。',['作業時間の記録','繰り返し部分の切り分け','入力・確認だけを支援する小さなツール']];}
function render(){if(step<0){app.className='card';app.innerHTML='<div class="kicker">✣ 5問・約1分で、改善できそうか無料チェック</div><h1>その面倒なPC作業、<br><em>もっとラクにできる？</em></h1><p class="lead">Excel・CSV・転記・集計・帳票などに対応</p><div class="examples"><span>▣ Excel・CSV</span><span>▱ 書類・ファイル整理</span></div><button class="primary" id="start">この作業、ラクにできるか見てみる　→</button><small class="privacy">✓ 5問・約1分／個人情報入力不要</small>';document.querySelector('#start').onclick=start;return}if(step<5){app.className='card question';app.innerHTML=`<div class="progress"><i style="width:${(step+1)*20}%"></i></div><p class="number">QUESTION ${step+1} / 5</p><h1>${esc(questions[step])}</h1><div class="choices">${choices.map(c=>`<button class="choice" data-v="${c[0]}"><b>${c[1]}</b><small>${c[2]}</small></button>`).join('')}</div><button class="back">← 前へ戻る</button>`;app.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>choose(b.dataset.v));app.querySelector('.back').onclick=()=>{step=step===0?-1:step-1;render()};return}const r=result();app.className='card result';app.innerHTML=`<div class="kicker">✓ 診断結果</div><h1>${r[0]}</h1><p class="summary">${r[1]}</p><div class="result-grid"><div><h2>検討できそうなこと</h2><ul>${r[2].map(x=>`<li>${x}</li>`).join('')}</ul></div><div><h2>確認しておきたいこと</h2><ul><li>使用中のシステムやファイル形式</li><li>毎回変わる判断や例外の有無</li><li>処理件数・頻度・希望する完成形</li></ul></div></div><div class="next"><h2>次に取れる行動</h2>まず1週間、作業の手順と所要時間をメモしてみましょう。具体的に相談したい場合は、個別の業務内容に合わせて実現方法・必要機能・概算費用・納期を整理します。</div><a class="cta" href="https://coconala.com/services/4398349" target="_blank" rel="noreferrer">あなたの作業を具体的に相談する　↗</a><p class="paid">3,000円相談では、アプリやツール本体ではなく、実現プランを文章で納品します。</p><button class="restart">↻ もう一度診断する</button><p class="disclaimer">実現可否は、使用環境・業務ルール・外部サービスの仕様や規約によって異なります。</p>`;app.querySelector('.cta').onclick=()=>track('coconala_click');app.querySelector('.restart').onclick=()=>{answers=Array(5).fill(null);start()}}
render();track('view');
